---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid.text
    name: UUID
    type: string
  - JSONPath: .spec.domain._type
    name: TYPE
    type: string
  - JSONPath: .spec.domain.vcpu.text
    name: CPU
    type: string
  - JSONPath: .spec.domain.memory.text
    name: RAM(KB)
    type: string
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    - vms
    singular: virtualmachine
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinenetworks.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: TYPE
    type: string
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineNetwork
    plural: virtualmachinenetworks
    shortNames:
    - vmn
    - vmns
    singular: virtualmachinenetwork
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachineimages.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid.text
    name: UUID
    type: string
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineImage
    plural: virtualmachineimages
    shortNames:
    - vmi
    - vmis
    singular: virtualmachineimage
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinedisks.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.volume.target.format._type
    name: TYPE
    type: string  
  - JSONPath: .spec.volume.target.path.text
    name: PATH
    type: string  
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineDisk
    plural: virtualmachinedisks
    shortNames:
    - vmd
    - vmds
    singular: virtualmachinedisk
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinesnapshots.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domainsnapshot.name.text
    name: NAME
    type: string
  - JSONPath: .spec.domainsnapshot.domain.name.text
    name: VM
    type: string  
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineSnapshot
    plural: virtualmachinesnapshots
    shortNames:
    - vmsn
    - vmsns
    singular: virtualmachinesnapshot
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: uitstoragepools.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.virtualMachineUITPool.data.poolname
    name: POOLNAME
    type: string
  - JSONPath: .spec.virtualMachineUITPool.data.url
    name: URL
    type: string
  - JSONPath: .spec.virtualMachineUITPool.data.mountpath
    name: MOUNTPATH
    type: string
  - JSONPath: .spec.virtualMachineUITPool.data.proto
    name: PROTO
    type: string
  - JSONPath: .spec.virtualMachineUITPool.data.free
    name: FREE
    type: integer
  - JSONPath: .spec.virtualMachineUITPool.data.used
    name: USED
    type: integer
  - JSONPath: .spec.virtualMachineUITPool.data.total
    name: TOTAL
    type: integer
  - JSONPath: .spec.virtualMachineUITPool.data.disktype
    name: DISKTYPE
    type: string
  - JSONPath: .spec.virtualMachineUITPool.result.msg
    name: STATUS
    type: string
  group: cloudplus.io
  names:
    kind: UITStoragePool
    plural: uitstoragepools
    shortNames:
      - usp
      - usps
    singular: uitstoragepool
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: uitdisks.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.data.name
    name: DISKNAME
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.data.poolname
    name: POOLNAME
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.data.size
    name: SIZE
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.data.filetype
    name: FILETYPE
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.data.path
    name: PATH
    type: string
  - JSONPath: .spec.virtualMachineUITDisk.result.msg
    name: STATUS
    type: string
  group: cloudplus.io
  names:
    kind: UITDisk
    plural: uitdisks
    shortNames:
      - ud
      - uds
    singular: uitdisk
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: uitsnapshots.cloudplus.io
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.nodeName
      name: NODE
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.poolname
      name: POOLNAME
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.name
      name: DISKNAME
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.sname
      name: SNAME
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.path
      name: PATH
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.filetype
      name: FILETYPE
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.date
      name: DATE
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.data.vmsize
      name: VMSIZE
      type: string
    - JSONPath: .spec.virtualMachineUITSnapshot.result.msg
      name: STATUS
      type: string
  group: cloudplus.io
  names:
    kind: UITSnapshot
    plural: uitsnapshots
    shortNames:
      - us
      - uss
    singular: uitsnapshot
  scope: Namespaced
  version: v1alpha3